apiVersion: cassandra.datastax.com/v1alpha2
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  # the name of the cassandra cluster
  clusterName: cluster1

  # the number server pods to provision
  size: 3

  # the distribution to use, "cassandra" or "dse" 
  serverType: cassandra

  # the image to use for the server
  serverImage: datastaxlabs/apache-cassandra-with-mgmtapi:3.11.6-20200316
  
  # the image to use for the config builder init container
  configBuilderImage: datastaxlabs/dse-k8s-config-builder:0.9.0-20200316

  # the version of the server
  imageVersion: "3.11.6"

  # management api cert authentication configuration
  managementApiAuth:
    insecure: {}

  # persistent storage configuration
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

  # logical rack definitions for the database
  racks:
    - name: r1
    - name: r2
    - name: r3

  # server configuration
  config:
    cassandra-yaml:
      num_tokens: 8
      file_cache_size_in_mb: 100
      memtable_space_in_mb: 100
    jvm-options:
      initial_heap_size: "1g"
      max_heap_size: "1g"
